"""Add scheduling columns

Revision ID: 2d007baeb998
Revises: 049013319117
Create Date: 2026-07-08 12:09:43.012936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d007baeb998'
down_revision: Union[str, Sequence[str], None] = '049013319117'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('emails', sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'sent_at')
    op.drop_column('emails', 'scheduled_at')
    # ### end Alembic commands ###
